# Global settings applied to the whole site. See more info here: https://www.netlify.com/docs/netlify-toml-reference/

[build]
command = "npm run production"
publish = "build_production"
environment = { PHP_VERSION = "7.2" }